# Configure paths to manifest files and output directories for dev/prod/test envs.

# Note: Base output directory of /public is assumed for static files
default: &default
  manifest: manifest.json
  # Used in your webpack configuration. Must be created in the
  # webpack_public_output_dir folder

development:
  <<: *default
  webpack_public_output_dir: webpack/development   # generated files for development, in /public/webpack/development
  hot_reloading_host: localhost:3500    # Default is localhost:3500. You can specify the protocol if needed. Defaults to http://.
  # Developer note: considering removing this option so it can ONLY be turned by using an ENV value.
  # Default is false, ENV 'HOT_RELOADING' will always override
  hot_reloading_enabled_by_default: false

test:
  <<: *default
  # generated files for tests, in /public/webpack/test
  webpack_public_output_dir: webpack/test

production:
  <<: *default
  # generated files for tests, in /public/webpack/production
  webpack_public_output_dir: webpack/production
